# Generated by Django 4.2.6 on 2023-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health_points', models.DecimalField(decimal_places=5, max_digits=10)),
                ('health_points_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('health_regeneration', models.DecimalField(decimal_places=5, max_digits=10)),
                ('health_regeneration_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mana', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mana_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mana_regeneration', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mana_regeneration_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('atack_damage', models.DecimalField(decimal_places=5, max_digits=10)),
                ('atack_damage_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('atack_speed', models.DecimalField(decimal_places=5, max_digits=10)),
                ('atack_speed_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('armor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('armor_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('magic_resistance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('magic_resistance_per_level', models.DecimalField(decimal_places=5, max_digits=10)),
                ('movement_speed', models.DecimalField(decimal_places=5, max_digits=20)),
                ('atack_range', models.DecimalField(decimal_places=5, max_digits=20)),
                ('classes', models.CharField(max_length=100)),
                ('blue_essence_price', models.IntegerField()),
                ('riot_points_price', models.IntegerField()),
            ],
        ),
    ]
