# Generated by Django 4.2.6 on 2023-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='atack_speed_per_level',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
